
package CLIENT;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


@WebService(name = "HelloWorld", targetNamespace = "http://SERVER/")
@XmlSeeAlso({ObjectFactory.class})

public interface HelloWorld 
{

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://SERVER/", className = "server.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://SERVER/", className = "server.SayHelloResponse")
    @Action(input = "http://SERVER/HelloWorld/sayHelloRequest", output = "http://SERVER/HelloWorld/sayHelloResponse")
    public String sayHello
    (
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);
}