
package CLIENT;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


@WebServiceClient(name = "HelloWorldImpService", targetNamespace = "http://SERVER/")
public class HelloWorldImpService extends Service
{
    private static URL HELLOWORLDIMPSERVICE_WSDL_LOCATION;
    private static WebServiceException HELLOWORLDIMPSERVICE_EXCEPTION;
    private final static QName HELLOWORLDIMPSERVICE_QNAME = new QName("http://SERVER/", "HelloWorldImpService");

    public static void setUrl(String passedUrl)
    {
    	URL url = null;
        WebServiceException e = null;
        try 
        {
            url = new URL(passedUrl);
        } 
        catch (MalformedURLException ex) 
        {
            e = new WebServiceException(ex);
        }
        HELLOWORLDIMPSERVICE_WSDL_LOCATION = url;
        HELLOWORLDIMPSERVICE_EXCEPTION = e;
    }

    public HelloWorldImpService() 
    {
        super(__getWsdlLocation(), HELLOWORLDIMPSERVICE_QNAME);
    }

    public HelloWorldImpService(WebServiceFeature... features) 
    {
        super(__getWsdlLocation(), HELLOWORLDIMPSERVICE_QNAME, features);
    }

    public HelloWorldImpService(URL wsdlLocation) 
    {
        super(wsdlLocation, HELLOWORLDIMPSERVICE_QNAME);
    }

    public HelloWorldImpService(URL wsdlLocation, WebServiceFeature... features) 
    {
        super(wsdlLocation, HELLOWORLDIMPSERVICE_QNAME, features);
    }

    public HelloWorldImpService(URL wsdlLocation, QName serviceName) 
    {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) 
    {
        super(wsdlLocation, serviceName, features);
    }

    @WebEndpoint(name = "HelloWorldImpPort")
    public HelloWorld getHelloWorldImpPort() 
    {
        return super.getPort(new QName("http://SERVER/", "HelloWorldImpPort"), HelloWorld.class);
    }

    @WebEndpoint(name = "HelloWorldImpPort")
    public HelloWorld getHelloWorldImpPort(WebServiceFeature... features) 
    {
        return super.getPort(new QName("http://SERVER/", "HelloWorldImpPort"), HelloWorld.class, features);
    }

    private static URL __getWsdlLocation() 
    {
        if (HELLOWORLDIMPSERVICE_EXCEPTION!= null) 
        {
            throw HELLOWORLDIMPSERVICE_EXCEPTION;
        }
        return HELLOWORLDIMPSERVICE_WSDL_LOCATION;
    }
}